### ISSUE TITLE
Please add the default information to this new repo 

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpn-did-resolution-service#1]
Hi @paullatzelsperger 

could you please add a little default description to this new repository.

updates https://github.com/eclipse-tractusx/.eclipsefdn/pull/62

Like for example described in our TRG´s e.g. https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1

Thanks in advance.

**Comment by paullatzelsperger** [comment]
@FaGru3n this will come with the initial code dump, which will be done by @jimmarino. I'll re-assign this issue.
